spring:
  application:
    name: gate-way
#  cloud:
#    gateway:
#      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/product/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka
